ASP.Net.MVC5.TrainingDemo/ASP.Net.MVC5.TrainingDemo/Controllers/StoreManagerController.cs
using ASP.Net.MVC5.TrainingDemo.Models;
using Demo.Core.Utilities;
using Demo.Domain;
using Demo.Provider.Provider;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ASP.Net.MVC5.TrainingDemo.Controllers
{
    public class StoreManagerController : Controller
    {
        private readonly IAlbumProvider _albumProvider;
        private readonly IGenreProvider _genreProvider;
        public List<CartListView> CartList
        {
            get
            {
                if(Session["CartList"]==null)
                {
                    return null;
                }
                else
                {
                    return Session["CartList"] as List<CartListView>;
                }
            }
            set
            {
                Session["CartList"] = value;
            }
        }
        public StoreManagerController(IAlbumProvider albumProvider,
            IGenreProvider genreProvider)
        {
            _albumProvider = albumProvider;
            _genreProvider = genreProvider;

        }
        // GET: StoreManager
        public ActionResult Store()
        {
            SetddlGenre();
            var _albumList = new List<AlbumViewModel>();
            _albumList = _albumProvider.GetAllAlbum();
            if (_albumList != null)
            {
                ViewBag.Album = _albumList;
                int pageindex = 1;
                var recordCount = _albumList.Count();
                if (Request.QueryString["page"] != null)
                    pageindex = Convert.ToInt32(Request.QueryString["page"]);
                const int PAGE_SZ = 15;

                ViewBag.Album = _albumList.OrderByDescending(alb => alb.AlbumId)
                    .Skip((pageindex - 1) * PAGE_SZ)
                    .Take(PAGE_SZ).ToList();
                ViewBag.Pager = new PagerHelper()
                {
                    PageIndex = pageindex,
                    PageSize = PAGE_SZ,
                    RecordCount = recordCount,
                };
            }
            else
            {
                ViewBag.Msg = "There are no data";
            }
            return View();
        }
        public async Task<ActionResult> Edit(int id,string type)
        {
            SetddlGenre();
            var album = new AlbumViewModel();
            album = await _albumProvider.GetAlbumById(id);
            return View(album);
        }
        public ActionResult Add()
        {
            SetddlGenre();
            return View();
        }
        public async Task<ActionResult> AlbumView(int id)
        {
            var model = new AlbumViewModel();
            model = await _albumProvider.GetAlbumById(id);
            return View(model);
        }
        public  void SetddlGenre()
        {
            var GenreList = new List<GenreViewModel>();
            if (_genreProvider.GetGenreListAsync() != null)
            {
                GenreList = _genreProvider.GetGenreListAsync();
            }
            ViewBag.GenreList= GenreList;
        }
        //[HttpPost]
        //public async Task<ActionResult> BuyAlbum(int id)
        //{ 
        //    var list = new CartListView();
        //    list.AlbumId = id;
        //    System.Web.HttpContext.Current.Session["CartList"] = list;

        //    return View();
        //}
        [HttpPost]
        public ActionResult Edit(AlbumViewModel album)
        {
            _albumProvider.UpdateAlbum(album);
            return Content("<script>alert('Update Success!');history.go(-1);</script>");
        }
        [HttpPost]
        public ActionResult Add(AlbumViewModel album)
        {
            _albumProvider.UpdateAlbum(album);
            return Content("<script>alert('Add Success!');history.go(-1);</script> ");
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var result = new DeleteMassage();
            int returnValue = _albumProvider.DeleteAlbum(id);
            if (returnValue == 0)
            {
                result.IsSuccess = true;
                result.ErrorMessage = "Delete success!";
            }

            else
            {
                result.IsSuccess = false;
                result.ErrorMessage = "The current Album has been deleted!";
            }

            return Json(result);
        }

        [HttpPost]
        public async Task<ActionResult> Store(AlbumViewModel album)
        {
            string GenreName = null; 
            var _album = new AlbumViewModel();
            var _albumList = new List<AlbumViewModel>();
            if(Request.Form.Count>0)
            {
                if (Request.Form.Get("GenreName") != "default")
                {
                    GenreName = Request.Form.Get("GenreName").ToString();
                }

            }
            else
            {
                if (Session["GenreName"] != null)
                    GenreName = Session["GenreName"].ToString();
            }

            System.Web.HttpContext.Current.Session["Title"] = album.Title;
            System.Web.HttpContext.Current.Session["GenreName"] = GenreName;
            System.Web.HttpContext.Current.Session["ArtistName"] = album.ArtistName;

            string title = album.Title;
            string ArtistName = album.ArtistName;
            if (title != null && GenreName == null && ArtistName == null)
            {
                album = await _albumProvider.GetAlbumByTittle(title);
                if (album != null)
                {
                    _albumList.Add(album);
                    ViewBag.Album = _albumList;
                    int pageindex = 1;
                    var recordCount = _albumList.Count();
                    if (Request.QueryString["page"] != null)
                        pageindex = Convert.ToInt32(Request.QueryString["page"]);
                    const int PAGE_SZ = 15;

                    ViewBag.Album = _albumList.OrderByDescending(art => art.AlbumId)
                       .Skip((pageindex - 1) * PAGE_SZ)
                       .Take(PAGE_SZ).ToList();
                    ViewBag.Pager = new PagerHelper()
                    {
                        PageIndex = pageindex,
                        PageSize = PAGE_SZ,
                        RecordCount = recordCount,
                    };
                }
                else
                {
                    ViewBag.Msg = "There are no data named " + title;
                }
            }
            else if (title == null && GenreName != null&& ArtistName == null)
            {
                _albumList = await _albumProvider.GetAlbumByGenre(GenreName);
                if (album != null)
                {
                    ViewBag.Album = _albumList;
                    int pageindex = 1;
                    var recordCount = _albumList.Count();
                    if (Request.QueryString["page"] != null)
                        pageindex = Convert.ToInt32(Request.QueryString["page"]);
                    const int PAGE_SZ = 15;

                    ViewBag.Album = _albumList.OrderByDescending(art => art.AlbumId)
                       .Skip((pageindex - 1) * PAGE_SZ)
                       .Take(PAGE_SZ).ToList();
                    ViewBag.Pager = new PagerHelper()
                    {
                        PageIndex = pageindex,
                        PageSize = PAGE_SZ,
                        RecordCount = recordCount,
                    };
                }
                else
                {
                    ViewBag.Msg = "There are no data named " + GenreName;
                }

            }
            else if (title == null && GenreName == null && ArtistName != null)
            {
                _albumList = await _albumProvider.GetAlbumByArtist(ArtistName);
                if (album != null)
                {
                    ViewBag.Album = _albumList;
                    int pageindex = 1;
                    var recordCount = _albumList.Count();
                    if (Request.QueryString["page"] != null)
                        pageindex = Convert.ToInt32(Request.QueryString["page"]);
                    const int PAGE_SZ = 15;

                    ViewBag.Album = _albumList.OrderByDescending(art => art.AlbumId)
                       .Skip((pageindex - 1) * PAGE_SZ)
                       .Take(PAGE_SZ).ToList();
                    ViewBag.Pager = new PagerHelper()
                    {
                        PageIndex = pageindex,
                        PageSize = PAGE_SZ,
                        RecordCount = recordCount,
                    };
                }
                else
                {
                    ViewBag.Msg = "There are no data named " + ArtistName;
                }

            }
            else if(title == null && GenreName == null && ArtistName == null&&album.PublicDate!=null)
            {
                _albumList = await _albumProvider.GetAlbumByDate(album.PublicDate);
                if (album != null)
                {
                    ViewBag.Album = _albumList;
                    int pageindex = 1;
                    var recordCount = _albumList.Count();
                    if (Request.QueryString["page"] != null)
                        pageindex = Convert.ToInt32(Request.QueryString["page"]);
                    const int PAGE_SZ = 15;

                    ViewBag.Album = _albumList.OrderByDescending(art => art.AlbumId)
                       .Skip((pageindex - 1) * PAGE_SZ)
                       .Take(PAGE_SZ).ToList();
                    ViewBag.Pager = new PagerHelper()
                    {
                        PageIndex = pageindex,
                        PageSize = PAGE_SZ,
                        RecordCount = recordCount,
                    };
                }
                else
                {

ASP.Net.MVC5.TrainingDemo/ASP.Net.MVC5.TrainingDemo/Views/StoreManager/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Demo.Domain.AlbumViewModel
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="/Scripts/jquery.validate.js"></script>
<script src="/Scripts/jquery.validate.unobtrusive.js"></script>

<h3 style="margin-top:50px;">@ViewBag.Title Album</h3>

@using (Html.BeginForm("Add", "StoreManager", new AjaxOptions { HttpMethod = "post", OnSuccess = "success" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="margin-top:10px;">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ArtistName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">

                    @Html.TextBoxFor(model => model.ArtistName, new { @class = "form-control", @style = "width:230px;height:36px" })
                    @Html.ValidationMessageFor(model => model.ArtistName, "", new { @class = "text-danger" })
                </div>


            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">

                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @style = "width:230px;height:36px" })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>


            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GenreName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group" style="width:230px">
                    <select id="GenreName" data-toggle="select" class="form-control select select-default" name="GenreName">
                        <option value="default" selected="selected">--Please select--</option>
                        @{
                            var Genrelist = ViewBag.GenreList as List<Demo.Domain.GenreViewModel>;
                            if (Genrelist != null && Genrelist.Count > 0)
                            {
                                foreach (var item in Genrelist)
                                {
                                    <option value="@item.GenreName">
                                        @item.GenreName
                                    </option>
                                }

                            }
                        }


                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">

                    @Html.TextBoxFor(model => model.Price, new { @class = "form-control", @style = "width:230px;height:36px" })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>


            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PublicDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group" style="width:450px">
                    <img id="1" style="cursor: pointer;" onclick="WdatePicker({el:'d2'})" src="../images/calendar.png">
                    @Html.TextBoxFor(model => model.PublicDate, new { id = "d2", onclick = "WdatePicker();", type = "text", placeholder = "mm/dd/yyyy", autocomplete = "off", @class = "form-control", @style = "width:200px" })
                </div>
                @Html.ValidationMessageFor(model => model.PublicDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <label style="color:red">@ViewBag.Msg</label>
        </div>
    </div>
}
<div>

    @Html.ActionLink("Back", "Store")
</div>
<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ASP.Net.MVC5.TrainingDemo/ASP.Net.MVC5.TrainingDemo/Views/StoreManager/AlbumView.cshtml
@{
    ViewBag.Title = "AlbumView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Demo.Domain.AlbumViewModel
<head>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>AlbumView</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7" style="height:600px; margin-top:30px;">
            <img width="450" height="450" src="~/images/album.png" class="img-circle" />
        </div>
        <div class="col-md-5" style="height:600px;">
            <div class="panel panel-default">
                <div class="panel-heading">Title</div>
                <div class="panel-body">
                    @Html.DisplayFor(model=>model.Title)
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Artist</h3>
                </div>
                <div class="panel-body">
                    @Html.DisplayFor(model=>model.ArtistName)
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Genre</h3>
                </div>
                <div class="panel-body">
                    @Html.DisplayFor(model => model.GenreName)
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">PublishDate</h3>
                </div>
                <div class="panel-body">
                    @Html.DisplayFor(model => model.PublicDate)
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Price</h3>
                </div>
                <div class="panel-body">
                    @Html.DisplayFor(model => model.Price)
                    @Html.Label("$")
                </div>
            </div>
        </div>

    </div>
    <div class="row" style="margin-top:20px">
        <div class="col-md-2" style="width:30%"></div>
        <div class="col-md-4" style="width:20%">
            <button id="Buy" type="submit" class="btn btn-danger " style="margin-left:10px;width:90px">Buy</button>
        </div>
        <div class="col-md-6" style="width:50%">
            <div class="col-md-8">
                <a href="#" class="btn btn-danger" style="margin-left:10px;width:90px">Cart</a>
            </div>
        </div>
    </div>
    <div>

        @Html.ActionLink("Back", "Store")
    </div>
</div>
    

ASP.Net.MVC5.TrainingDemo/ASP.Net.MVC5.TrainingDemo/Views/StoreManager/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Demo.Domain.AlbumViewModel
<script src="~/Scripts/jquery-3.3.1.js"></script>
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@ViewBag.Type Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.AlbumId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AlbumId, htmlAttributes: new { @style = "width:230px;height:34px;background:#CCCCCC", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.AlbumId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ArtistName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">

                    @Html.TextBoxFor(model => model.ArtistName, new { @class = "form-control", @style = "width:230px;height:36px" })
                    @Html.ValidationMessageFor(model => model.ArtistName, "", new { @class = "text-danger" })
                </div>


            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">

                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @style = "width:230px;height:36px" })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>


            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GenreName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group" style="width:230px">
                    <select id="GenreName" data-toggle="select" class="form-control select select-default" name="GenreName">
                        <option value="default" selected="selected">--Please select--</option>
                        @{
                            var Genrelist = ViewBag.GenreList as List<Demo.Domain.GenreViewModel>;
                            if (Genrelist != null && Genrelist.Count > 0)
                            {
                                foreach (var item in Genrelist)
                                {
                                    <option value="@item.GenreName">
                                        @item.GenreName
                                    </option>
                                }

                            }
                        }


                    </select>
                </div>


            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">

                    @Html.TextBoxFor(model => model.Price, new { @class = "form-control", @style = "width:230px;height:36px" })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>


            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PublicDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group" style="width:450px">
                    <img id="1" style="cursor: pointer;" onclick="WdatePicker({el:'d2'})" src="~/images/calendar.png">
                    @Html.TextBoxFor(model => model.PublicDate, new { id = "d2", onclick = "WdatePicker();", type = "text", placeholder = "mm/dd/yyyy", autocomplete = "off", @class = "form-control", @style = "width:200px" })
                </div>
                @Html.ValidationMessageFor(model => model.PublicDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <label style="color:red">@ViewBag.Msg</label>
        </div>
    </div>
}
<div>

    @Html.ActionLink("Back", "Store")
</div>